import type { ElementLabel } from './element.types';

export interface DativeValenceConfig {
  valenceElectrons: number;
  valenceOrbitals: number;
}

export const DATIVE_VALENCE_TABLE: Record<ElementLabel, DativeValenceConfig> = {
  H: { valenceElectrons: 1, valenceOrbitals: 1 },
  He: { valenceElectrons: 2, valenceOrbitals: 1 },
  Li: { valenceElectrons: 1, valenceOrbitals: 4 },
  Be: { valenceElectrons: 2, valenceOrbitals: 4 },
  B: { valenceElectrons: 3, valenceOrbitals: 4 },
  C: { valenceElectrons: 4, valenceOrbitals: 4 },
  N: { valenceElectrons: 5, valenceOrbitals: 4 },
  O: { valenceElectrons: 6, valenceOrbitals: 4 },
  F: { valenceElectrons: 7, valenceOrbitals: 4 },
  Ne: { valenceElectrons: 8, valenceOrbitals: 4 },
  Na: { valenceElectrons: 1, valenceOrbitals: 4 },
  Mg: { valenceElectrons: 2, valenceOrbitals: 9 },
  Al: { valenceElectrons: 3, valenceOrbitals: 4 },
  Si: { valenceElectrons: 4, valenceOrbitals: 4 },
  P: { valenceElectrons: 5, valenceOrbitals: 4 },
  S: { valenceElectrons: 6, valenceOrbitals: 4 },
  Cl: { valenceElectrons: 7, valenceOrbitals: 4 },
  Ar: { valenceElectrons: 8, valenceOrbitals: 4 },
  K: { valenceElectrons: 1, valenceOrbitals: 4 },
  Ca: { valenceElectrons: 2, valenceOrbitals: 9 },
  Sc: { valenceElectrons: 3, valenceOrbitals: 9 },
  Ti: { valenceElectrons: 4, valenceOrbitals: 9 },
  V: { valenceElectrons: 5, valenceOrbitals: 9 },
  Cr: { valenceElectrons: 6, valenceOrbitals: 9 },
  Mn: { valenceElectrons: 7, valenceOrbitals: 9 },
  Fe: { valenceElectrons: 8, valenceOrbitals: 9 },
  Co: { valenceElectrons: 9, valenceOrbitals: 9 },
  Ni: { valenceElectrons: 10, valenceOrbitals: 9 },
  Cu: { valenceElectrons: 11, valenceOrbitals: 9 },
  Zn: { valenceElectrons: 12, valenceOrbitals: 9 },
  Ga: { valenceElectrons: 3, valenceOrbitals: 4 },
  Ge: { valenceElectrons: 4, valenceOrbitals: 4 },
  As: { valenceElectrons: 5, valenceOrbitals: 4 },
  Se: { valenceElectrons: 6, valenceOrbitals: 4 },
  Br: { valenceElectrons: 7, valenceOrbitals: 4 },
  Kr: { valenceElectrons: 8, valenceOrbitals: 4 },
  Rb: { valenceElectrons: 1, valenceOrbitals: 4 },
  Sr: { valenceElectrons: 2, valenceOrbitals: 9 },
  Y: { valenceElectrons: 3, valenceOrbitals: 9 },
  Zr: { valenceElectrons: 4, valenceOrbitals: 9 },
  Nb: { valenceElectrons: 5, valenceOrbitals: 9 },
  Mo: { valenceElectrons: 6, valenceOrbitals: 9 },
  Tc: { valenceElectrons: 7, valenceOrbitals: 9 },
  Ru: { valenceElectrons: 8, valenceOrbitals: 9 },
  Rh: { valenceElectrons: 9, valenceOrbitals: 9 },
  Pd: { valenceElectrons: 10, valenceOrbitals: 9 },
  Ag: { valenceElectrons: 11, valenceOrbitals: 9 },
  Cd: { valenceElectrons: 12, valenceOrbitals: 9 },
  In: { valenceElectrons: 3, valenceOrbitals: 4 },
  Sn: { valenceElectrons: 4, valenceOrbitals: 4 },
  Sb: { valenceElectrons: 5, valenceOrbitals: 4 },
  Te: { valenceElectrons: 6, valenceOrbitals: 4 },
  I: { valenceElectrons: 7, valenceOrbitals: 4 },
  Xe: { valenceElectrons: 8, valenceOrbitals: 4 },
  Cs: { valenceElectrons: 1, valenceOrbitals: 4 },
  Ba: { valenceElectrons: 2, valenceOrbitals: 9 },
  La: { valenceElectrons: 3, valenceOrbitals: 16 },
  Ce: { valenceElectrons: 4, valenceOrbitals: 16 },
  Pr: { valenceElectrons: 5, valenceOrbitals: 16 },
  Nd: { valenceElectrons: 6, valenceOrbitals: 16 },
  Pm: { valenceElectrons: 7, valenceOrbitals: 16 },
  Sm: { valenceElectrons: 8, valenceOrbitals: 16 },
  Eu: { valenceElectrons: 9, valenceOrbitals: 16 },
  Gd: { valenceElectrons: 10, valenceOrbitals: 16 },
  Tb: { valenceElectrons: 11, valenceOrbitals: 16 },
  Dy: { valenceElectrons: 12, valenceOrbitals: 16 },
  Ho: { valenceElectrons: 13, valenceOrbitals: 16 },
  Er: { valenceElectrons: 14, valenceOrbitals: 16 },
  Tm: { valenceElectrons: 15, valenceOrbitals: 16 },
  Yb: { valenceElectrons: 16, valenceOrbitals: 16 },
  Lu: { valenceElectrons: 3, valenceOrbitals: 9 },
  Hf: { valenceElectrons: 4, valenceOrbitals: 9 },
  Ta: { valenceElectrons: 5, valenceOrbitals: 9 },
  W: { valenceElectrons: 6, valenceOrbitals: 9 },
  Re: { valenceElectrons: 7, valenceOrbitals: 9 },
  Os: { valenceElectrons: 8, valenceOrbitals: 9 },
  Ir: { valenceElectrons: 9, valenceOrbitals: 9 },
  Pt: { valenceElectrons: 10, valenceOrbitals: 9 },
  Au: { valenceElectrons: 11, valenceOrbitals: 9 },
  Hg: { valenceElectrons: 12, valenceOrbitals: 9 },
  Tl: { valenceElectrons: 3, valenceOrbitals: 4 },
  Pb: { valenceElectrons: 4, valenceOrbitals: 4 },
  Bi: { valenceElectrons: 5, valenceOrbitals: 4 },
  Po: { valenceElectrons: 6, valenceOrbitals: 4 },
  At: { valenceElectrons: 7, valenceOrbitals: 4 },
  Rn: { valenceElectrons: 8, valenceOrbitals: 4 },
  Fr: { valenceElectrons: 1, valenceOrbitals: 4 },
  Ra: { valenceElectrons: 2, valenceOrbitals: 9 },
  Ac: { valenceElectrons: 3, valenceOrbitals: 16 },
  Th: { valenceElectrons: 4, valenceOrbitals: 16 },
  Pa: { valenceElectrons: 5, valenceOrbitals: 16 },
  U: { valenceElectrons: 6, valenceOrbitals: 16 },
  Np: { valenceElectrons: 7, valenceOrbitals: 16 },
  Pu: { valenceElectrons: 8, valenceOrbitals: 16 },
  Am: { valenceElectrons: 9, valenceOrbitals: 16 },
  Cm: { valenceElectrons: 10, valenceOrbitals: 16 },
  Bk: { valenceElectrons: 11, valenceOrbitals: 16 },
  Cf: { valenceElectrons: 12, valenceOrbitals: 16 },
  Es: { valenceElectrons: 13, valenceOrbitals: 16 },
  Fm: { valenceElectrons: 14, valenceOrbitals: 16 },
  Md: { valenceElectrons: 15, valenceOrbitals: 16 },
  No: { valenceElectrons: 16, valenceOrbitals: 16 },
  Lr: { valenceElectrons: 3, valenceOrbitals: 9 },
  Rf: { valenceElectrons: 4, valenceOrbitals: 9 },
  Db: { valenceElectrons: 5, valenceOrbitals: 9 },
  Sg: { valenceElectrons: 6, valenceOrbitals: 9 },
  Bh: { valenceElectrons: 7, valenceOrbitals: 9 },
  Hs: { valenceElectrons: 8, valenceOrbitals: 9 },
  Mt: { valenceElectrons: 9, valenceOrbitals: 9 },
  Ds: { valenceElectrons: 10, valenceOrbitals: 9 },
  Rg: { valenceElectrons: 11, valenceOrbitals: 9 },
  Cn: { valenceElectrons: 12, valenceOrbitals: 9 },
  Nh: { valenceElectrons: 3, valenceOrbitals: 4 },
  Fl: { valenceElectrons: 4, valenceOrbitals: 4 },
  Mc: { valenceElectrons: 5, valenceOrbitals: 4 },
  Lv: { valenceElectrons: 6, valenceOrbitals: 4 },
  Ts: { valenceElectrons: 7, valenceOrbitals: 4 },
  Og: { valenceElectrons: 8, valenceOrbitals: 4 },
};

export const DATIVE_IMPLICIT_HYDROGEN_LABELS: ReadonlySet<ElementLabel> =
  new Set<ElementLabel>([
    'H',
    'Li',
    'B',
    'C',
    'N',
    'O',
    'F',
    'Na',
    'Al',
    'Si',
    'P',
    'S',
    'Cl',
    'K',
    'Ga',
    'Ge',
    'As',
    'Se',
    'Br',
    'Rb',
    'In',
    'Sn',
    'Sb',
    'Te',
    'I',
    'Cs',
    'Tl',
    'Pb',
    'Bi',
    'Po',
    'At',
    'Fr',
  ]);
