addReviewers: true
numberOfReviewers: 1
useReviewGroups: true
addAssignees: author
reviewGroups:
  core:
    - nitvex
    - yuleicul
    - rrodionov91
  developers:
    - AnastasiiaPlyako
    - gairon
    - Inga-Vishnivetskaia
    - StarlaStarla
    - Iogsotot
    - SashaGraves
  qa:
    - AleksandraSmolianinova
    - Ustianskii
    - Vehemen
    - Zhirnoff
