addReviewers: true
numberOfReviewers: 1
useReviewGroups: true
addAssignees: author
reviewGroups:
  core:
    - nitvex
    - yuleicul
    - rrodionov91
  developers:
    - StarlaStarla
    - aproskurnov
    - NatalliaHutovich
    - vitaepam
    - SashaGraves
