addReviewers: true
numberOfReviewers: 1
useReviewGroups: true
addAssignees: author
reviewGroups:
  core:
    - nitvex
    - rrodionov91
  developers:
    - StarlaStarla
    - chgayane
  QA:
    - Zhirnoff
    - ViktoriaTkacheva
    - urszula-gawlowska