addReviewers: true
numberOfReviewers: 1
useReviewGroups: true
addAssignees: author
reviewGroups:
  core:
    - nitvex
    - KonstantinEpam23
    - rrodionov91
  developers:
    - StarlaStarla
    - aproskurnov
    - NatalliaHutovich
    - vitaepam
    - SashaGraves
    - nanoblit
    - chgayane
    - AKZhuk
  QA:
    - Zhirnoff
    - AleksandraSmolianinova
    - MartaWilliams
    - y-holik
    - AnastasiyaPiatrovaKlu