addReviewers: true
numberOfReviewers: 1
useReviewGroups: true
addAssignees: author
reviewGroups:
  core:
    - nitvex
    - rrodionov91
    - SashaGraves
    - AKZhuk
    - yuleicul
  developers:
    - nanoblit
    - StarlaStarla
    - chgayane
    - OlgaMazurina
  QA:
    - Zhirnoff
    - MartaWilliams
    - y-holik
    - AnastasiyaPiatrovaKlu
    - ViktoriaTkacheva