addReviewers: true

numberOfReviewers: 1

useReviewGroups: true

addAssignees: author

reviewGroups:
  core:
    - nitvex
    - yuleicul
    - KonstantinEpam23

  developers:
    - VandaPonikarova
    - VasilevDO
    - AnastasiiaPlyako