addReviewers: true
numberOfReviewers: 1
useReviewGroups: true
addAssignees: author
reviewGroups:
  core:
    - svvald
    - rrodionov91
  developers:
    - NataliaLoginova
  QA:
    - Zhirnoff
    - AlexeyGirin