addReviewers: true
numberOfReviewers: 1
useReviewGroups: true
addAssignees: author
reviewGroups:
  core:
    - ilya-asiyuk-epam
    - rrodionov91
  developers:
    - StarlaStarla
    - chgayane
  QA:
    - Zhirnoff
    - AlexeyGirin