groups:
  - name: core
    reviewers: 1
    usernames:
      - nitvex
      - yuleicul
      - KonstantinEpam23

  - name: developers
    reviewers: 1
    usernames:
      - VandaPonikarova
      - VasilevDO
      - AnastasiiaPlyako