// This file needs to handle import generated by emcripten wasm compiler.
// Inside js file generated by emscripten there is a line:
// scriptDirectory=require("url").fileURLToPath(new URL("./",import.meta.url))
// To allow builders resolve this import we need to add this file and use it as an index entry point.

// Package main entry point and package.json exports use main.ts file.
