const fieldGroups = {
  resetToSelect: 'general',
  rotationStep: 'general',
  showValenceWarnings: 'general',
  atomColoring: 'general',
  font: 'general',
  fontsz: 'general',
  fontszsub: 'general',
  showStereoFlags: 'stereo',
  stereoLabelStyle: 'stereo',
  colorOfAbsoluteCenters: 'stereo',
  colorOfAndCenters: 'stereo',
  colorOfOrCenters: 'stereo',
  colorStereogenicCenters: 'stereo',
  autoFadeOfStereoLabels: 'stereo',
  absFlagLabel: 'stereo',
  andFlagLabel: 'stereo',
  orFlagLabel: 'stereo',
  mixedFlagLabel: 'stereo',
  ignoreChiralFlag: 'stereo',
  carbonExplicitly: 'atoms',
  showCharge: 'atoms',
  showValence: 'atoms',
  showHydrogenLabels: 'atoms',
  aromaticCircle: 'bonds',
  bondSpacing: 'bonds',
  bondThickness: 'bonds',
  stereoBondWidth: 'bonds',
  'smart-layout': 'server',
  'ignore-stereochemistry-errors': 'server',
  'mass-skip-error-on-pseudoatoms': 'server',
  'gross-formula-add-rsites': 'server',
  'gross-formula-add-isotopes': 'server',
  miewMode: '3dviewer',
  miewTheme: '3dviewer',
  miewAtomLabel: '3dviewer',
  showAtomIds: 'debugging',
  showBondIds: 'debugging',
  showHalfBondIds: 'debugging',
  showLoopIds: 'debugging',
};

export default fieldGroups;
