import { i18n } from 'ketcher-react';

// Generated by scripts/generate-locale-resources.mjs from whatever locale
// directories exist under src/locales/ — see that file for the rationale
// (static imports for Rollup tree-shaking despite a discovered, not
// hand-maintained, locale list). Adding or removing a language is a
// src/locales/<code>/ directory change plus `npm run i18n:generate`, not an
// edit to this file.
import {
  BASE_RESOURCES,
  EXTRA_LOCALE_RESOURCES,
} from './localeResources.generated';

const MULTI_LANGUAGE_BUILD =
  process.env.KETCHER_MULTI_LANGUAGE_BUILD === 'true';

/**
 * ketcher-macromolecules renders inside ketcher-react's <I18nextProvider>
 * (see Editor.tsx), so it reuses that shared i18next instance instead of
 * standing up its own. Namespaces are merged in here via addResourceBundle
 * rather than added to ketcher-react's own i18n.ts, to avoid a reverse
 * ketcher-react -> ketcher-macromolecules source dependency (macromolecules
 * already depends on react, not the other way around).
 */
i18n.addResourceBundle('en', 'macromolecules', BASE_RESOURCES.macromolecules);
i18n.addResourceBundle(
  'en',
  'macromoleculesDialogs',
  BASE_RESOURCES.macromoleculesDialogs,
);

if (MULTI_LANGUAGE_BUILD) {
  for (const [locale, resources] of Object.entries(EXTRA_LOCALE_RESOURCES)) {
    i18n.addResourceBundle(locale, 'macromolecules', resources.macromolecules);
    i18n.addResourceBundle(
      locale,
      'macromoleculesDialogs',
      resources.macromoleculesDialogs,
    );
  }
}
