export enum BondTypeName {
  Single = 'Single Bond',
  Double = 'Double Bond',
  Triple = 'Triple',
  Any = 'Any',
  Aromatic = 'Aromatic',
  SingleDouble = 'Single/Double',
  SingleAromatic = 'Single/Aromatic',
  DoubleAromatic = 'Double/Aromatic',
  Dative = 'Dative',
  Hydrogen = 'Hydrogen',
  SingleUp = 'Single Up',
  SingleDown = 'Single Down',
  SingleUpDown = 'Single Up/Down',
  DoubleCisTrans = 'Double Cis/Trans',
}
