export enum MoleculesFileFormatType {
  KetFormat = 'Ket Format-option',
  MDLMolfileV2000 = 'MDL Molfile V2000-option',
  MDLMolfileV3000 = 'MDL Molfile V3000-option',
  MDLRxnfileV2000 = 'MDL Rxnfile V2000-option',
  MDLRxnfileV3000 = 'MDL Rxnfile V3000-option',
  SDFV2000 = 'SDF V2000-option',
  SDFV3000 = 'SDF V3000-option',
  RDFV2000 = 'RDF V2000-option',
  RDFV3000 = 'RDF V3000-option',
  DaylightSMARTS = 'Daylight SMARTS-option',
  DaylightSMILES = 'Daylight SMILES-option',
  ExtendedSMILES = 'Extended SMILES-option',
  CML = 'CML-option',
  InChI = 'InChI-option',
  InChIAuxInfo = 'InChI AuxInfo-option',
  InChIKey = 'InChIKey-option',
  SVGDocument = 'SVG Document-option',
  PNGImage = 'PNG Image-option',
  CDXML = 'CDXML-option',
  Base64CDX = 'Base64 CDX-option',
  CDX = 'CDX-option',
}

export enum MoleculesFileFormatName {
  KetFormat = 'Ket Format',
  MDLMolfileV2000 = 'MDL Molfile V2000',
  MDLMolfileV3000 = 'MDL Molfile V3000',
  MDLRxnfileV2000 = 'MDL Rxnfile V2000',
  MDLRxnfileV3000 = 'MDL Rxnfile V3000',
  SDFV2000 = 'SDF V2000',
  SDFV3000 = 'SDF V3000',
  RDFV2000 = 'RDF V2000',
  RDFV3000 = 'RDF V3000',
  DaylightSMARTS = 'Daylight SMARTS',
  DaylightSMILES = 'Daylight SMILES',
  ExtendedSMILES = 'Extended SMILES',
  CML = 'CML',
  InChI = 'InChI',
  InChIAuxInfo = 'InChI AuxInfo',
  InChIKey = 'InChIKey',
  SVGDocument = 'SVG Document',
  PNGImage = 'PNG Image',
  CDXML = 'CDXML',
  Base64CDX = 'Base64 CDX',
  CDX = 'CDX',
}
