export enum ArrowType {
  ArrowOpenAngle = 'reaction-arrow-open-angle',
  ArrowFilledTriangle = 'reaction-arrow-filled-triangle',
  ArrowFilledBow = 'reaction-arrow-filled-bow',
  ArrowDashedOpenAngle = 'reaction-arrow-dashed-open-angle',
  FailedArrow = 'reaction-arrow-failed',
  RetrosyntheticArrow = 'reaction-arrow-retrosynthetic',
  ArrowBothEndsFilledTriangle = 'reaction-arrow-both-ends-filled-triangle',
  ArrowEquilibriumFilledHalfBow = 'reaction-arrow-equilibrium-filled-half-bow',
  ArrowEquilibriumFilledTriangle = 'reaction-arrow-equilibrium-filled-triangle',
  ArrowEquilibriumOpenAngle = 'reaction-arrow-equilibrium-open-angle',
  ArrowUnbalancedEquilibriumFilledHalfBow = 'reaction-arrow-unbalanced-equilibrium-filled-half-bow',
  ArrowUnbalancedEquilibriumOpenHalfAngle = 'reaction-arrow-unbalanced-equilibrium-open-half-angle',
  ArrowUnbalancedEquilibriumLargeFilledHalfBow = 'reaction-arrow-unbalanced-equilibrium-large-filled-half-bow',
  ArrowUnbalancedEquilibriumFilledHalfTriangle = 'reaction-arrow-unbalanced-equilibrium-filled-half-triangle',
  ArrowEllipticalArcFilledBow = 'reaction-arrow-elliptical-arc-arrow-filled-bow',
  ArrowEllipticalArcFilledTriangle = 'reaction-arrow-elliptical-arc-arrow-filled-triangle',
  ArrowEllipticalArcOpenAngle = 'reaction-arrow-elliptical-arc-arrow-open-angle',
  ArrowEllipticalArcOpenHalfAngle = 'reaction-arrow-elliptical-arc-arrow-open-half-angle',
  MultiTailedArrow = 'reaction-arrow-multitail',
}
