/* eslint-disable prettier/prettier */
export enum TabSection {
  TemplateLibraryTab = 'template-library-tab',
  FunctionalGroupsTab = 'functional-groups-tab',
  SaltsAndSolventsTab = 'salts-and-solvents-tab',
}

// Items on Template Library Tab
export enum TemplateLibraryTabItems {
  AlphaDSugars = 'alpha-D-Sugars-accordion-item',
  Aromatics = 'Aromatics-accordion-item',
  BetaDSugars = 'beta-D-Sugars-accordion-item',
  Bicycles = 'Bicycles-accordion-item',
  BridgedPolycyclics = 'Bridged Polycyclics-accordion-item',
  CrownEthers = 'Crown Ethers-accordion-item',
  DAminoAcids = 'D-Amino Acids-accordion-item',
  DSugars = 'D-Sugars-accordion-item',
  HeterocyclicRings = 'Heterocyclic Rings-accordion-item',
  LAminoAcids = 'L-Amino Acids-accordion-item',
  Nucleobases = 'Nucleobases-accordion-item',
  Rings = 'Rings-accordion-item',
  Sugars = 'Sugars-accordion-item',
  ThreeDTemplates = '3D Templates-accordion-item',
}

// Options for every Item on Template Library Tab
export enum AlphaDSugarsOption {
  AlphaDAllopyranose = 'alpha-D-Allopyranose',
  AlphaDAltropyranose = 'alpha-D-Altropyranose',
  AlphaDArabinofuranose = 'alpha-D-Arabinofuranose',
  AlphaDArabinopyranose = 'alpha-D-Arabinopyranose',
  AlphaDErythrofuranose = 'alpha-D-Erythrofuranose',
  AlphaDGalactopyranose = 'alpha-D-Galactopyranose',
  AlphaDGlucopyranose = 'alpha-D-Glucopyranose',
  AlphaDGulopyranose = 'alpha-D-Gulopyranose',
  AlphaDIdopyranose = 'alpha-D-Idopyranose',
  AlphaDLyxofuranose = 'alpha-D-Lyxofuranose',
  AlphaDLyxopyranose = 'alpha-D-Lyxopyranose',
  AlphaDMannopyranose = 'alpha-D-Mannopyranose',
  AlphaDPsicofuranose = 'alpha-D-Psicofuranose',
  AlphaDRibofuranose = 'alpha-D-Ribofuranose',
  AlphaDRibopyranose = 'alpha-D-Ribopyranose',
  AlphaDSorbofuranose = 'alpha-D-Sorbofuranose',
  AlphaDTagatofuranose = 'alpha-D-Tagatofuranose',
  AlphaDTalopyranose = 'alpha-D-Talopyranose',
  AlphaDThreofuranose = 'alpha-D-Threofuranose',
  AlphaDXylofuranose = 'alpha-D-Xylofuranose',
  AlphaDXylopyranose = 'alpha-D-Xylopyranose',
}

export enum AromaticsOption {
  Cyclopenta13diene = 'Cyclopenta-1,3-diene',
  OneHindene = '1H-indene',
  Naphtalene = 'Naphtalene',
  Azulene = 'Azulene',
  EStilbene = 'E-Stilbene',
  ZStilbene = 'Z-Stilbene',
  Anthracene = 'Anthracene',
  Phenantrene = 'Phenantrene',
  Pyrene = 'Pyrene',
  Triphenylene = 'Triphenylene',
  Triptycene = 'Triptycene',
  FourteenAnnulene = '14-Annulene',
  EighteenAnnulene = '18-Annulene',
  Porphyrin = 'Porphyrin',
  Phthalocyanine = 'Phthalocyanine',
  C60 = 'C60',
  C80 = 'C80',
  PhenylalanineMustard = 'Phenylalanine mustard',
}

export enum BetaDSugarsOption {
  BetaDAllopyranose = 'beta-D-Allopyranose',
  BetaDAltropyranose = 'beta-D-Altropyranose',
  BetaDArabinofuranose = 'beta-D-Arabinofuranose',
  BetaDArabinopyranose = 'beta-D-Arabinopyranose',
  BetaDErythrofuranose = 'beta-D-Erythrofuranose',
  BetaDFructofuranose = 'beta-D-Fructofuranose',
  BetaDGalactopyranose = 'beta-D-Galactopyranose',
  BetaDGlucopyranose = 'beta-D-Glucopyranose',
  BetaDGulopyranose = 'beta-D-Gulopyranose',
  BetaDIdopyranose = 'beta-D-Idopyranose',
  BetaDLyxofuranose = 'beta-D-Lyxofuranose',
  BetaDLyxopyranose = 'beta-D-Lyxopyranose',
  BetaDMannopyranose = 'beta-D-Mannopyranose',
  BetaDPsicofuranose = 'beta-D-Psicofuranose',
  BetaDRibofuranose = 'beta-D-Ribofuranose',
  BetaDRibopyranose = 'beta-D-Ribopyranose',
  BetaDSorbofuranose = 'beta-D-Sorbofuranose',
  BetaDTagatofuranose = 'beta-D-Tagatofuranose',
  BetaDTalopyranose = 'beta-D-Talopyranose',
  BetaDThreofuranose = 'beta-D-Threofuranose',
  BetaDXylofuranose = 'beta-D-Xylofuranose',
  BetaDXylopyranose = 'beta-D-Xylopyranose',
}

export enum BicyclesOption {
  Bicyclo111Pentane = 'Bicyclo[1-1-1]pentane',
  Bicyclo211Hexane = 'Bicyclo[2-1-1]hexane',
  Bicyclo221Heptane = 'Bicyclo[2-2-1]heptane',
  Bicyclo311Heptane = 'Bicyclo[3-1-1]heptane',
  Bicyclo222Octane = 'Bicyclo[2-2-2]octane',
  Bicyclo321Octane = 'Bicyclo[3-2-1]octane',
  Bicyclo411Octane = 'Bicyclo[4-1-1]octane',
  Bicyclo322Nonane = 'Bicyclo[3-2-2]nonane',
  Bicyclo331Nonane = 'Bicyclo[3-3-1]nonane',
  Bicyclo421Nonane = 'Bicyclo[4-2-1]nonane',
  Bicyclo511Nonane = 'Bicyclo[5-1-1]nonane',
  Bicyclo332Decane = 'Bicyclo[3-3-2]decane',
  Bicyclo422Decane = 'Bicyclo[4-2-2]decane',
  Bicyclo431Decane = 'Bicyclo[4-3-1]decane',
  Bicyclo521Decane = 'Bicyclo[5-2-1]decane',
  Bicyclo333Undecane = 'Bicyclo[3-3-3]undecane',
  Bicyclo432Undecane = 'Bicyclo[4-3-2]undecane',
  Bicyclo441Undecane = 'Bicyclo[4-4-1]undecane',
  Bicyclo531Undecane = 'Bicyclo[5-3-1]undecane',
  Bicyclo442Dodecane = 'Bicyclo[4-4-2]dodecane',
  Bicyclo532Dodecane = 'Bicyclo[5-3-2]dodecane',
  Bicyclo541Dodecane = 'Bicyclo[5-4-1]dodecane',
  Bicyclo533Tridecane = 'Bicyclo[5-3-3]tridecane',
  Bicyclo542Tridecane = 'Bicyclo[5-4-2]tridecane',
  Bicyclo551Tridecane = 'Bicyclo[5-5-1]tridecane',
}

export enum BridgedPolycyclicsOption {
  Adamantane = 'Adamantane',
  Cubane = 'Cubane',
  Prismane = 'Prismane',
  Twistane = 'Twistane',
}

export enum CrownEthersOption {
  TwelveCrown4 = '12-Crown-4',
  ThirteenCrown4 = '13-Crown-4',
  FourteenCrown4 = '14-Crown-4',
  FifteenCrown5 = '15-Crown-5',
  SixteenCrown5 = '16-Crown-5',
  SeventeenCrown5 = '17-Crown-5',
  EighteenCrown6 = '18-Crown-6',
  TwentyCrown6 = '20-Crown-6',
  TwentyOneCrown7 = '21-Crown-7',
  TwentyFourCrown8 = '24-Crown-8',
  TwentySevenCrown9 = '27-Crown-9',
  ThirtyCrown10 = '30-Crown-10',
}

export enum DAminoAcidsOption {
  ALADAlanine = 'ALA-D-Alanine',
  ARGDArginine = 'ARG-D-Arginine',
  ASNDAsparagine = 'ASN-D-Asparagine',
  ASPDAsparticAcid = 'ASP-D-Aspartic acid',
  CYSDCysteine = 'CYS-D-Cysteine',
  GLNDGlutamine = 'GLN-D-Glutamine',
  GLUDGlutamicAcid = 'GLU-D-Glutamic acid',
  GLYGlycine = 'GLY-Glycine',
  HISDHistidine = 'HIS-D-Histidine',
  ILEDIsoleucine = 'ILE-D-Isoleucine',
  LEUDLeucine = 'LEU-D-Leucine',
  LYSDLysine = 'LYS-D-Lysine',
  METDMethionine = 'MET-D-Methionine',
  PHEDPhenylalanine = 'PHE-D-Phenylalanine',
  PRODProline = 'PRO-D-Proline',
  SERDSerine = 'SER-D-Serine',
  THRDThreonine = 'THR-D-Threonine',
  TRPDTryptophan = 'TRP-D-Tryptophan',
  TYRDTyrosine = 'TYR-D-Tyrosine',
  VALDValine = 'VAL-D-Valine',
}

export enum DSugarsOption {
  DAllose = 'D-Allose',
  DAltrose = 'D-Altrose',
  DArabinose = 'D-Arabinose',
  DErythrose = 'D-Erythrose',
  DErythrulose = 'D-Erythrulose',
  DFructose = 'D-Fructose',
  DGalactose = 'D-Galactose',
  DGlucose = 'D-Glucose',
  DGulose = 'D-Gulose',
  DIdose = 'D-Idose',
  DLyxose = 'D-Lyxose',
  DMannose = 'D-Mannose',
  DPsicose = 'D-Psicose',
  DRibose = 'D-Ribose',
  DRibulose = 'D-Ribulose',
  DSorbose = 'D-Sorbose',
  DTagatose = 'D-Tagatose',
  DTalose = 'D-Talose',
  DThreose = 'D-Threose',
  DXylose = 'D-Xylose',
  DXylulose = 'D-Xylulose',
}

export enum HeterocyclicRingsOption {
  OneTwoThreeOxadiazole = '1_2_3-Oxadiazole',
  Dioxane = 'Dioxane',
  Furan = 'Furan',
  Imidazole = 'Imidazole',
  Indole = 'Indole',
  Isoquinoline = 'Isoquinoline',
  Isoxazole = 'Isoxazole',
  Morpholine = 'Morpholine',
  Oxazole = 'Oxazole',
  Piperazine = 'Piperazine',
  Piperidine = 'Piperidine',
  Purine = 'Purine',
  Pyran = 'Pyran',
  Pyrazine = 'Pyrazine',
  Pyrazol = 'Pyrazol',
  Pyridazine = 'Pyridazine',
  Pyridine = 'Pyridine',
  Pyridone = 'Pyridone',
  Pyrimidine = 'Pyrimidine',
  Pyrole = 'Pyrole',
  Pyrone = 'Pyrone',
  Pyrrolidine = 'Pyrrolidine',
  Quinoline = 'Quinoline',
  Tetrahydrofuran = 'Tetrahydrofuran',
  Tetrahydrothiophene = 'Tetrahydrothiophene',
  Tetrazole = 'Tetrazole',
  Thiophene = 'Thiophene',
  Triazine = 'Triazine',
  Triazole = 'Triazole',
}

export enum LAminoAcidsOption {
  ALALAlanine = 'ALA-L-Alanine',
  ARGLArginine = 'ARG-L-Arginine',
  ASNLAsparagine = 'ASN-L-Asparagine',
  ASPLAsparticAcid = 'ASP-L-Aspartic acid',
  CYSLCysteine = 'CYS-L-Cysteine',
  GLNLGlutamine = 'GLN-L-Glutamine',
  GLULGlutamicAcid = 'GLU-L-Glutamic acid',
  GLYGlycine = 'GLY-Glycine',
  HISLHistidine = 'HIS-L-Histidine',
  ILELIsoleucine = 'ILE-L-Isoleucine',
  LEULLeucine = 'LEU-L-Leucine',
  LYSLLysine = 'LYS-L-Lysine',
  METLMethionine = 'MET-L-Methionine',
  PHELPhenylalanine = 'PHE-L-Phenylalanine',
  PROLProline = 'PRO-L-Proline',
  SERLSerine = 'SER-L-Serine',
  THRLThreonine = 'THR-L-Threonine',
  TRPLTryptophan = 'TRP-L-Tryptophan',
  TYRLTyrosine = 'TYR-L-Tyrosine',
  VALLValine = 'VAL-L-Valine',
}

export enum NucleobasesOption {
  Adenine = 'Adenine',
  Cytosine = 'Cytosine',
  Guanine = 'Guanine',
  Thymine = 'Thymine',
  Uracil = 'Uracil',
  Ribose = 'Ribose',
  Deoxyribose = 'Deoxyribose',
  RiboseMonophosphate = 'Ribose monophosphate',
  DeoxyriboseMonophosphate = 'Deoxyribose monophosphate',
  AdenosineMonophosphate = 'Adenosine monophosphate',
  AdenosineDiphosphate = 'Adenosine diphosphate',
  AdenosineTriphosphate = 'Adenosine triphosphate',
}

export enum RingsOption {
  Benzene = 'Benzene',
  Boat = 'Boat',
  Chair = 'Chair',
  Chair1 = 'Chair1',
  Chair2 = 'Chair2',
  Chair3 = 'Chair3',
  Chair4 = 'Chair4',
  Cyclopentadiene = 'Cyclopentadiene',
  Ring3 = 'Ring3',
  Ring4 = 'Ring4',
  Ring5 = 'Ring5',
  Ring6 = 'Ring6',
  Ring7 = 'Ring7',
  Ring8 = 'Ring8',
  Ring9 = 'Ring9',
  Ring10 = 'Ring10',
  Ring11 = 'Ring11',
  Ring12 = 'Ring12',
  Ring13 = 'Ring13',
  Ring14 = 'Ring14',
  Ring15 = 'Ring15',
  Ring16 = 'Ring16',
  Ring18 = 'Ring18',
  Ring20 = 'Ring20',
  Ring21 = 'Ring21',
}

export enum SugarsOption {
  AlphaDAllopyranose = 'alpha-D-Allopyranose',
  AlphaDAltropyranose = 'alpha-D-Altropyranose',
  AlphaDGalactopyranose = 'alpha-D-Galactopyranose',
  AlphaDGlucopyranose = 'alpha-D-Glucopyranose',
  AlphaDGulopyranose = 'alpha-D-Gulopyranose',
  AlphaDIdopyranose = 'alpha-D-Idopyranose',
  AlphaDMannopyranose = 'alpha-D-Mannopyranose',
  AlphaDTalopyranose = 'alpha-D-Talopyranose',
}

export enum ThreeDTemplatesOption {
  FullereneC60 = 'fullerene C60',
  Adamantane = 'adamantane',
  Cubane = 'cubane',
  Ring6Boat = 'ring 6 boat',
  Ring6Chair = 'ring 6 chair',
  FerroceneCovalent = 'Ferrocene_covalent',
  FerroceneHaptic = 'Ferrocene_haptic',
  BisBenzeneChromiumHaptic = 'bis(benzene)chromium_haptic',
  BisBenzeneChromiumCovalent = 'bis(benzene)chromium_covalent',
  Dodecaborate = 'Dodecaborate',
  VitaminB12Dative = 'Vitamin B12_dative',
  VitaminB12Covalent = 'Vitamin B12_covalent',
  Sucrose = 'sucrose',
  HeptamolybdateIonDative = 'Heptamolybdate ion_dative',
  HeptamolybdateIonCovalent = 'Heptamolybdate ion_covalent',
  C20H20 = 'C20H20',
  TetracobaltDodecacarbonylDative = 'Tetracobalt dodecacarbonyl_dative',
  TetracobaltDodecacarbonylCovalent = 'Tetracobalt dodecacarbonyl_covalent',
  IronPentacarbonylDative = 'Iron pentacarbonyl_dative',
  IronPentacarbonylCovalent = 'Iron pentacarbonyl_covalent',
  ChlorophyllADative = 'Chlorophyll A_dative',
  ChlorophyllACovalent = 'Chlorophyll A_covalent',
}

// Edit functionality for every Item on Template Library Tab
export enum EditAlphaDSugarsOption {
  EditAlphaDAllopyranose = 'edit-alpha-D-Allopyranose-button',
  EditAlphaDAltropyranose = 'edit-alpha-D-Altropyranose-button',
  EditAlphaDArabinofuranose = 'edit-alpha-D-Arabinofuranose-button',
  EditAlphaDArabinopyranose = 'edit-alpha-D-Arabinopyranose-button',
  EditAlphaDErythrofuranose = 'edit-alpha-D-Erythrofuranose-button',
  EditAlphaDGalactopyranose = 'edit-alpha-D-Galactopyranose-button',
  EditAlphaDGlucopyranose = 'edit-alpha-D-Glucopyranose-button',
  EditAlphaDGulopyranose = 'edit-alpha-D-Gulopyranose-button',
  EditAlphaDIdopyranose = 'edit-alpha-D-Idopyranose-button',
  EditAlphaDLyxofuranose = 'edit-alpha-D-Lyxofuranose-button',
  EditAlphaDLyxopyranose = 'edit-alpha-D-Lyxopyranose-button',
  EditAlphaDMannopyranose = 'edit-alpha-D-Mannopyranose-button',
  EditAlphaDPsicofuranose = 'edit-alpha-D-Psicofuranose-button',
  EditAlphaDRibofuranose = 'edit-alpha-D-Ribofuranose-button',
  EditAlphaDRibopyranose = 'edit-alpha-D-Ribopyranose-button',
  EditAlphaDSorbofuranose = 'edit-alpha-D-Sorbofuranose-button',
  EditAlphaDTagatofuranose = 'edit-alpha-D-Tagatofuranose-button',
  EditAlphaDTalopyranose = 'edit-alpha-D-Talopyranose-button',
  EditAlphaDThreofuranose = 'edit-alpha-D-Threofuranose-button',
  EditAlphaDXylofuranose = 'edit-alpha-D-Xylofuranose-button',
  EditAlphaDXylopyranose = 'edit-alpha-D-Xylopyranose-button',
}

export enum EditAromaticsOption {
  EditCyclopenta13diene = 'edit-Cyclopenta-1,3-diene-button',
  EditOneHindene = 'edit-1H-indene-button',
  EditNaphtalene = 'edit-Naphtalene-button',
  EditAzulene = 'edit-Azulene-button',
  EditEStilbene = 'edit-E-Stilbene-button',
  EditZStilbene = 'edit-Z-Stilbene-button',
  EditAnthracene = 'edit-Anthracene-button',
  EditPhenantrene = 'edit-Phenantrene-button',
  EditPyrene = 'edit-Pyrene-button',
  EditTriphenylene = 'edit-Triphenylene-button',
  EditTriptycene = 'edit-Triptycene-button',
  EditFourteenAnnulene = 'edit-14-Annulene-button',
  EditEighteenAnnulene = 'edit-18-Annulene-button',
  EditPorphyrin = 'edit-Porphyrin-button',
  EditPhthalocyanine = 'edit-Phthalocyanine-button',
  EditC60 = 'edit-C60-button',
  EditC80 = 'edit-C80-button',
  EditPhenylalanineMustard = 'edit-Phenylalanine-mustard-button',
}

export enum EditBetaDSugarsOption {
  EditBetaDAllopyranose = 'edit-beta-D-Allopyranose-button',
  EditBetaDAltropyranose = 'edit-beta-D-Altropyranose-button',
  EditBetaDArabinofuranose = 'edit-beta-D-Arabinofuranose-button',
  EditBetaDArabinopyranose = 'edit-beta-D-Arabinopyranose-button',
  EditBetaDErythrofuranose = 'edit-beta-D-Erythrofuranose-button',
  EditBetaDFructofuranose = 'edit-beta-D-Fructofuranose-button',
  EditBetaDGalactopyranose = 'edit-beta-D-Galactopyranose-button',
  EditBetaDGlucopyranose = 'edit-beta-D-Glucopyranose-button',
  EditBetaDGulopyranose = 'edit-beta-D-Gulopyranose-button',
  EditBetaDIdopyranose = 'edit-beta-D-Idopyranose-button',
  EditBetaDLyxofuranose = 'edit-beta-D-Lyxofuranose-button',
  EditBetaDLyxopyranose = 'edit-beta-D-Lyxopyranose-button',
  EditBetaDMannopyranose = 'edit-beta-D-Mannopyranose-button',
  EditBetaDPsicofuranose = 'edit-beta-D-Psicofuranose-button',
  EditBetaDRibofuranose = 'edit-beta-D-Ribofuranose-button',
  EditBetaDRibopyranose = 'edit-beta-D-Ribopyranose-button',
  EditBetaDSorbofuranose = 'edit-beta-D-Sorbofuranose-button',
  EditBetaDTagatofuranose = 'edit-beta-D-Tagatofuranose-button',
  EditBetaDTalopyranose = 'edit-beta-D-Talopyranose-button',
  EditBetaDThreofuranose = 'edit-beta-D-Threofuranose-button',
  EditBetaDXylofuranose = 'edit-beta-D-Xylofuranose-button',
  EditBetaDXylopyranose = 'edit-beta-D-Xylopyranose-button',
}

export enum EditBicyclesOption {
  EditBicyclo111Pentane = 'edit-Bicyclo[1-1-1]pentane-button',
  EditBicyclo211Hexane = 'edit-Bicyclo[2-1-1]hexane-button',
  EditBicyclo221Heptane = 'edit-Bicyclo[2-2-1]heptane-button',
  EditBicyclo311Heptane = 'edit-Bicyclo[3-1-1]heptane-button',
  EditBicyclo222Octane = 'edit-Bicyclo[2-2-2]octane-button',
  EditBicyclo321Octane = 'edit-Bicyclo[3-2-1]octane-button',
  EditBicyclo411Octane = 'edit-Bicyclo[4-1-1]octane-button',
  EditBicyclo322Nonane = 'edit-Bicyclo[3-2-2]nonane-button',
  EditBicyclo331Nonane = 'edit-Bicyclo[3-3-1]nonane-button',
  EditBicyclo421Nonane = 'edit-Bicyclo[4-2-1]nonane-button',
  EditBicyclo511Nonane = 'edit-Bicyclo[5-1-1]nonane-button',
  EditBicyclo332Decane = 'edit-Bicyclo[3-3-2]decane-button',
  EditBicyclo422Decane = 'edit-Bicyclo[4-2-2]decane-button',
  EditBicyclo431Decane = 'edit-Bicyclo[4-3-1]decane-button',
  EditBicyclo521Decane = 'edit-Bicyclo[5-2-1]decane-button',
  EditBicyclo333Undecane = 'edit-Bicyclo[3-3-3]undecane-button',
  EditBicyclo432Undecane = 'edit-Bicyclo[4-3-2]undecane-button',
  EditBicyclo441Undecane = 'edit-Bicyclo[4-4-1]undecane-button',
  EditBicyclo531Undecane = 'edit-Bicyclo[5-3-1]undecane-button',
  EditBicyclo442Dodecane = 'edit-Bicyclo[4-4-2]dodecane-button',
  EditBicyclo532Dodecane = 'edit-Bicyclo[5-3-2]dodecane-button',
  EditBicyclo541Dodecane = 'edit-Bicyclo[5-4-1]dodecane-button',
  EditBicyclo533Tridecane = 'edit-Bicyclo[5-3-3]tridecane-button',
  EditBicyclo542Tridecane = 'edit-Bicyclo[5-4-2]tridecane-button',
  EditBicyclo551Tridecane = 'edit-Bicyclo[5-5-1]tridecane-button',
}

export enum EditBridgedPolycyclicsOption {
  EditAdamantane = 'edit-Adamantane-button',
  EditCubane = 'edit-Cubane-button',
  EditPrismane = 'edit-Prismane-button',
  EditTwistane = 'edit-Twistane-button',
}

export enum EditCrownEthersOption {
  EditTwelveCrown4 = 'edit-12-Crown-4-button',
  EditThirteenCrown4 = 'edit-13-Crown-4-button',
  EditFourteenCrown4 = 'edit-14-Crown-4-button',
  EditFifteenCrown5 = 'edit-15-Crown-5-button',
  EditSixteenCrown5 = 'edit-16-Crown-5-button',
  EditSeventeenCrown5 = 'edit-17-Crown-5-button',
  EditEighteenCrown6 = 'edit-18-Crown-6-button',
  EditTwentyCrown6 = 'edit-20-Crown-6-button',
  EditTwentyOneCrown7 = 'edit-21-Crown-7-button',
  EditTwentyFourCrown8 = 'edit-24-Crown-8-button',
  EditTwentySevenCrown9 = 'edit-27-Crown-9-button',
  EditThirtyCrown10 = 'edit-30-Crown-10-button',
}

export enum EditDAminoAcidsOption {
  EditALADAlanine = 'edit-ALA-D-Alanine-button',
  EditARGDArginine = 'edit-ARG-D-Arginine-button',
  EditASNDAsparagine = 'edit-ASN-D-Asparagine-button',
  EditASPDAsparticAcid = 'edit-ASP-D-Aspartic-acid-button',
  EditCYSDCysteine = 'edit-CYS-D-Cysteine-button',
  EditGLNDGlutamine = 'edit-GLN-D-Glutamine-button',
  EditGLUDGlutamicAcid = 'edit-GLU-D-Glutamic-acid-button',
  EditGLYGlycine = 'edit-GLY-Glycine-button',
  EditHISDHistidine = 'edit-HIS-D-Histidine-button',
  EditILEDIsoleucine = 'edit-ILE-D-Isoleucine-button',
  EditLEUDLeucine = 'edit-LEU-D-Leucine-button',
  EditLYSDLysine = 'edit-LYS-D-Lysine-button',
  EditMETDMethionine = 'edit-MET-D-Methionine-button',
  EditPHEDPhenylalanine = 'edit-PHE-D-Phenylalanine-button',
  EditPRODProline = 'edit-PRO-D-Proline-button',
  EditSERDSerine = 'edit-SER-D-Serine-button',
  EditTHRDThreonine = 'edit-THR-D-Threonine-button',
  EditTRPDTryptophan = 'edit-TRP-D-Tryptophan-button',
  EditTYRDTyrosine = 'edit-TYR-D-Tyrosine-button',
  EditVALDValine = 'edit-VAL-D-Valine-button',
}

export enum EditDSugarsOption {
  EditDAllose = 'edit-D-Allose-button',
  EditDAltrose = 'edit-D-Altrose-button',
  EditDArabinose = 'edit-D-Arabinose-button',
  EditDErythrose = 'edit-D-Erythrose-button',
  EditDErythrulose = 'edit-D-Erythrulose-button',
  EditDFructose = 'edit-D-Fructose-button',
  EditDGalactose = 'edit-D-Galactose-button',
  EditDGlucose = 'edit-D-Glucose-button',
  EditDGulose = 'edit-D-Gulose-button',
  EditDIdose = 'edit-D-Idose-button',
  EditDLyxose = 'edit-D-Lyxose-button',
  EditDMannose = 'edit-D-Mannose-button',
  EditDPsicose = 'edit-D-Psicose-button',
  EditDRibose = 'edit-D-Ribose-button',
  EditDRibulose = 'edit-D-Ribulose-button',
  EditDSorbose = 'edit-D-Sorbose-button',
  EditDTagatose = 'edit-D-Tagatose-button',
  EditDTalose = 'edit-D-Talose-button',
  EditDThreose = 'edit-D-Threose-button',
  EditDXylose = 'edit-D-Xylose-button',
  EditDXylulose = 'edit-D-Xylulose-button',
}

export enum EditHeterocyclicRingsOption {
  EditOneTwoThreeOxadiazole = 'edit-1_2_3-Oxadiazole-button',
  EditDioxane = 'edit-Dioxane-button',
  EditFuran = 'edit-Furan-button',
  EditImidazole = 'edit-Imidazole-button',
  EditIndole = 'edit-Indole-button',
  EditIsoquinoline = 'edit-Isoquinoline-button',
  EditIsoxazole = 'edit-Isoxazole-button',
  EditMorpholine = 'edit-Morpholine-button',
  EditOxazole = 'edit-Oxazole-button',
  EditPiperazine = 'edit-Piperazine-button',
  EditPiperidine = 'edit-Piperidine-button',
  EditPurine = 'edit-Purine-button',
  EditPyran = 'edit-Pyran-button',
  EditPyrazine = 'edit-Pyrazine-button',
  EditPyrazol = 'edit-Pyrazol-button',
  EditPyridazine = 'edit-Pyridazine-button',
  EditPyridine = 'edit-Pyridine-button',
  EditPyridone = 'edit-Pyridone-button',
  EditPyrimidine = 'edit-Pyrimidine-button',
  EditPyrole = 'edit-Pyrole-button',
  EditPyrone = 'edit-Pyrone-button',
  EditPyrrolidine = 'edit-Pyrrolidine-button',
  EditQuinoline = 'edit-Quinoline-button',
  EditTetrahydrofuran = 'edit-Tetrahydrofuran-button',
  EditTetrahydrothiophene = 'edit-Tetrahydrothiophene-button',
  EditTetrazole = 'edit-Tetrazole-button',
  EditThiophene = 'edit-Thiophene-button',
  EditTriazine = 'edit-Triazine-button',
  EditTriazole = 'edit-Triazole-button',
}

export enum EditLAminoAcidsOption {
  EditALALAlanine = 'edit-ALA-L-Alanine-button',
  EditARGLArginine = 'edit-ARG-L-Arginine-button',
  EditASNLAsparagine = 'edit-ASN-L-Asparagine-button',
  EditASPLAsparticAcid = 'edit-ASP-L-Aspartic-acid-button',
  EditCYSLCysteine = 'edit-CYS-L-Cysteine-button',
  EditGLNLGlutamine = 'edit-GLN-L-Glutamine-button',
  EditGLULGlutamicAcid = 'edit-GLU-L-Glutamic-acid-button',
  EditGLYGlycine = 'edit-GLY-Glycine-button',
  EditHISLHistidine = 'edit-HIS-L-Histidine-button',
  EditILELIsoleucine = 'edit-ILE-L-Isoleucine-button',
  EditLEULLeucine = 'edit-LEU-L-Leucine-button',
  EditLYSLLysine = 'edit-LYS-L-Lysine-button',
  EditMETLMethionine = 'edit-MET-L-Methionine-button',
  EditPHELPhenylalanine = 'edit-PHE-L-Phenylalanine-button',
  EditPROLProline = 'edit-PRO-L-Proline-button',
  EditSERLSerine = 'edit-SER-L-Serine-button',
  EditTHRLThreonine = 'edit-THR-L-Threonine-button',
  EditTRPLTryptophan = 'edit-TRP-L-Tryptophan-button',
  EditTYRLTyrosine = 'edit-TYR-L-Tyrosine-button',
  EditVALLValine = 'edit-VAL-L-Valine-button',
}

export enum EditNucleobasesOption {
  EditAdenine = 'edit-Adenine-button',
  EditCytosine = 'edit-Cytosine-button',
  EditGuanine = 'edit-Guanine-button',
  EditThymine = 'edit-Thymine-button',
  EditUracil = 'edit-Uracil-button',
  EditRibose = 'edit-Ribose-button',
  EditDeoxyribose = 'edit-Deoxyribose-button',
  EditRiboseMonophosphate = 'edit-Ribose monophosphate-button',
  EditDeoxyriboseMonophosphate = 'edit-Deoxyribose monophosphate-button',
  EditAdenosineMonophosphate = 'edit-Adenosine monophosphate-button',
  EditAdenosineDiphosphate = 'edit-Adenosine diphosphate-button',
  EditAdenosineTriphosphate = 'edit-Adenosine triphosphate-button',
}

export enum EditRingsOption {
  EditBenzene = 'edit-Benzene-button',
  EditBoat = 'edit-Boat-button',
  EditChair = 'edit-Chair-button',
  EditChair1 = 'edit-Chair1-button',
  EditChair2 = 'edit-Chair2-button',
  EditChair3 = 'edit-Chair3-button',
  EditChair4 = 'edit-Chair4-button',
  EditCyclopentadiene = 'edit-Cyclopentadiene-button',
  EditRing3 = 'edit-Ring3-button',
  EditRing4 = 'edit-Ring4-button',
  EditRing5 = 'edit-Ring5-button',
  EditRing6 = 'edit-Ring6-button',
  EditRing7 = 'edit-Ring7-button',
  EditRing8 = 'edit-Ring8-button',
  EditRing9 = 'edit-Ring9-button',
  EditRing10 = 'edit-Ring10-button',
  EditRing11 = 'edit-Ring11-button',
  EditRing12 = 'edit-Ring12-button',
  EditRing13 = 'edit-Ring13-button',
  EditRing14 = 'edit-Ring14-button',
  EditRing15 = 'edit-Ring15-button',
  EditRing16 = 'edit-Ring16-button',
  EditRing18 = 'edit-Ring18-button',
  EditRing20 = 'edit-Ring20-button',
  EditRing21 = 'edit-Ring21-button',
}

export enum EditSugarsOption {
  EditAlphaDAllopyranose = 'edit-alpha-D-Allopyranose-button',
  EditAlphaDAltropyranose = 'edit-alpha-D-Altropyranose-button',
  EditAlphaDGalactopyranose = 'edit-alpha-D-Galactopyranose-button',
  EditAlphaDGlucopyranose = 'edit-alpha-D-Glucopyranose-button',
  EditAlphaDGulopyranose = 'edit-alpha-D-Gulopyranose-button',
  EditAlphaDIdopyranose = 'edit-alpha-D-Idopyranose-button',
  EditAlphaDMannopyranose = 'edit-alpha-D-Mannopyranose-button',
  EditAlphaDTalopyranose = 'edit-alpha-D-Talopyranose-button',
}

export enum EditThreeDTemplatesOption {
  EditFullereneC60 = 'edit-fullerene C60-button',
  EditAdamantane = 'edit-adamantane-button',
  EditCubane = 'edit-cubane-button',
  EditRing6Boat = 'edit-ring 6 boat-button',
  EditRing6Chair = 'edit-ring 6 chair-button',
  EditFerroceneCovalent = 'edit-Ferrocene_covalent-button',
  EditFerroceneHaptic = 'edit-Ferrocene_haptic-button',
  EditBisBenzeneChromiumHaptic = 'edit-bis(benzene)chromium_haptic-button',
  EditBisBenzeneChromiumCovalent = 'edit-bis(benzene)chromium_covalent-button',
  EditDodecaborate = 'edit-Dodecaborate-button',
  EditVitaminB12Dative = 'edit-Vitamin B12_dative-button',
  EditVitaminB12Covalent = 'edit-Vitamin B12_covalent-button',
  EditSucrose = 'edit-sucrose-button',
  EditHeptamolybdateIonDative = 'edit-Heptamolybdate ion_dative-button',
  EditHeptamolybdateIonCovalent = 'edit-Heptamolybdate ion_covalent-button',
  EditC20H20 = 'edit-C20H20-button',
  EditTetracobaltDodecacarbonylDative = 'edit-Tetracobalt dodecacarbonyl_dative-button',
  EditTetracobaltDodecacarbonylCovalent = 'edit-Tetracobalt dodecacarbonyl_covalent-button',
  EditIronPentacarbonylDative = 'edit-Iron pentacarbonyl_dative-button',
  EditIronPentacarbonylCovalent = 'edit-Iron pentacarbonyl_covalent-button',
  EditChlorophyllADative = 'edit-Chlorophyll A_dative-button',
  EditChlorophyllACovalent = 'edit-Chlorophyll A_covalent-button',
}

// Items on Functional Groups Tab
export enum FunctionalGroupsTabItems {
  Ac = 'Ac',
  Bn = 'Bn',
  Boc = 'Boc',
  Bu = 'Bu',
  Bz = 'Bz',
  Cbz = 'Cbz',
  C2H5 = 'C2H5',
  CCl3 = 'CCl3',
  CF3 = 'CF3',
  Cn = 'CN',
  CO2Et = 'CO2Et',
  CO2H = 'CO2H',
  CO2Me = 'CO2Me',
  CONH2 = 'CONH2',
  CO2Pr = 'CO2Pr',
  CO2tBu = 'CO2tBu',
  Cp = 'Cp',
  CPh3 = 'CPh3',
  Cy = 'Cy',
  Et = 'Et',
  FMOC = 'FMOC',
  IBu = 'iBu',
  Indole = 'Indole',
  IPr = 'iPr',
  Me = 'Me',
  Mes = 'Mes',
  Ms = 'Ms',
  NCO = 'NCO',
  NCS = 'NCS',
  NHPh = 'NHPh',
  NO2 = 'NO2',
  OAc = 'OAc',
  OCF3 = 'OCF3',
  OCN = 'OCN',
  OEt = 'OEt',
  OMe = 'OMe',
  Ph = 'Ph',
  PhCOOH = 'PhCOOH',
  Piv = 'Piv',
  PO2 = 'PO2',
  PO3 = 'PO3',
  PO3H2 = 'PO3H2',
  PO4 = 'PO4',
  PO4H2 = 'PO4H2',
  Pr = 'Pr',
  SBu = 'sBu',
  SCN = 'SCN',
  SO2 = 'SO2',
  SO2Cl = 'SO2Cl',
  SO2H = 'SO2H',
  SO3 = 'SO3',
  SO3H = 'SO3H',
  SO4 = 'SO4',
  SO4H = 'SO4H',
  Ster = 'ster',
  TBDMS = 'TBDMS',
  TBDPS = 'TBDPS',
  TBu = 'tBu',
  Tf = 'Tf',
  TMS = 'TMS',
  Tos = 'Tos',
  Ts = 'Ts',
}

// Items on Salts And Solvents Tab
export enum SaltsAndSolventsTabItems {
  AceticAcid = 'acetic acid',
  AceticAnhydride = 'acetic anhydride',
  FormicAcid = 'formic acid',
  MethaneSulphonicAcid = 'methane sulphonic acid',
  PropionicAcid = 'propionic acid',
  OneTwoPropanediol = '1,2-propanediol',
  OneThreePropanediol = '1,3-propanediol',
  OneFourButanediol = '1,4-butanediol',
  OneButanol = '1-butanol',
  OnePropanol = '1-propanol',
  TwoButanol = '2-butanol',
  TwoEthylhexanol = '2-ethylhexanol',
  Isopropanol = 'isopropanol',
  TwoMethoxyethanol = '2-methoxyethanol',
  TwoPentanol = '2-pentanol',
  BenzylAlcohol = 'benzyl alcohol',
  Cyclohexanol = 'cyclohexanol',
  Ethanol = 'ethanol',
  EthyleneGlycol = 'ethylene glycol',
  Glycerol = 'glycerol',
  IsoamylAlcohol = 'isoamyl alcohol',
  Isobutanol = 'isobutanol',
  Methanol = 'methanol',
  TButanol = 't-butanol',
  Water = 'water',
  CarbonDioxide = 'carbon dioxide',
  Benzene = 'benzene',
  Cumene = 'cumene',
  Mesitylene = 'mesitylene',
  Toluene = 'toluene',
  NnDimethylaniline = 'n,n-dimethylaniline',
  Pyridine = 'pyridine',
  Triethylamine = 'triethylamine',
  Acetonitrile = 'acetonitrile',
  DimethylAcetamide = 'dimethyl acetamide',
  DimethylFormamide = 'dimethyl formamide',
  DimethylSulfoxide = 'dimethyl sulfoxide',
  DimethylpropyleneUrea = 'dimethylpropylene urea',
  Formamide = 'formamide',
  NMethyl2Pyrrolidone = 'n-methyl-2-pyrrolidone',
  NMethylformamide = 'n-methylformamide',
  PropaneNitrile = 'propane nitrile',
  Sulfolane = 'sulfolane',
  AmylAcetate = 'amyl acetate',
  ButylAcetate = 'butyl acetate',
  DimethylCarbonate = 'dimethyl carbonate',
  EthylAcetate = 'ethyl acetate',
  EthylFormate = 'ethyl formate',
  EthylLactate = 'ethyl lactate',
  EthylPropionate = 'ethyl propionate',
  EthyleneCarbonate = 'ethylene carbonate',
  IsobutylAcetate = 'isobutyl acetate',
  IsopropylAcetate = 'isopropyl acetate',
  MethylAcetate = 'methyl acetate',
  MethylFormate = 'methyl formate',
  MethylLactate = 'methyl lactate',
  NOctylacetate = 'n-octylacetate',
  PropylAcetate = 'propyl acetate',
  PropyleneCarbonate = 'propylene carbonate',
  TButylAcetate = 't-butyl acetate',
  OneTwoDimethoxyethane = '1,2-dimethoxyethane',
  OneFourDioxane = '1,4-dioxane',
  TwoMethylTetrahydrofuran = '2-methyl tetrahydrofuran',
  Anisole = 'anisole',
  ButylCarbitol = 'butyl carbitol',
  CyclopentylMethylEther = 'cyclopentyl methyl ether',
  DibutylEther = 'dibutyl ether',
  DiethylEther = 'diethyl ether',
  DiethyleneGlycol = 'diethylene glycol',
  Diglyme = 'diglyme',
  DiisopropylEther = 'diisopropyl ether',
  DimethylEther = 'dimethyl ether',
  DiphenylEther = 'diphenyl ether',
  Ethoxybenzene = 'ethoxybenzene',
  MethylTButylEther = 'methyl t-butyl ether',
  TAmylMethylEther = 't-amyl methyl ether',
  TButylethylEther = 't-butylethyl ether',
  Tetrahydrofuran = 'tetrahydrofuran',
  TriethyleneGlycol = 'triethylene glycol',
  OneTwoFourTrichlorobenzene = '1,2,4-trichlorobenzene',
  OneTwoDichlorobenzene = '1,2-dichlorobenzene',
  OneTwoDichloroethane = '1,2-dichloroethane',
  TwoTwoTwoTrifluoroethanol = '2,2,2-trifluoroethanol',
  TwoThreeFourTrifluorotoluene = '2,3,4-trifluorotoluene',
  CarbonTetrachloride = 'carbon tetrachloride',
  ChloroaceticAcid = 'chloroacetic acid',
  Chlorobenzene = 'chlorobenzene',
  Chloroform = 'chloroform',
  Dichloromethane = 'dichloromethane',
  Fluorobenzene = 'fluorobenzene',
  PerfluorocyclicEther = 'perfluorocyclic ether',
  Perfluorocyclohexane = 'perfluorocyclohexane',
  Perfluorohexane = 'perfluorohexane',
  Perfluorotoluene = 'perfluorotoluene',
  TrichloroaceticAcid = 'trichloroacetic acid',
  Trichloroacetonitrile = 'trichloroacetonitrile',
  TrifluoroaceticAcid = 'trifluoroacetic acid',
  Trifluoromethylbenzene = 'trifluoromethylbenzene',
  TwoMethylpentane = '2-methylpentane',
  CisDecalin = 'cis-decalin',
  Cyclohexane = 'cyclohexane',
  Isooctane = 'isooctane',
  Methylcyclohexane = 'methylcyclohexane',
  Methylcyclopentane = 'methylcyclopentane',
  Heptane = 'heptane',
  Hexane = 'hexane',
  Pentane = 'pentane',
  TwoPentanone = '2-pentanone',
  ThreePentanone = '3-pentanone',
  Acetone = 'acetone',
  Cyclohexanone = 'cyclohexanone',
  Cyclopentanone = 'cyclopentanone',
  MethylEthylKetone = 'methyl ethyl ketone',
  MethylIsobutylKetone = 'methyl isobutyl ketone',
  CarbonDisulfide = 'carbon disulfide',
  Nitromethane = 'nitromethane',
  OXylene = 'o-xylene',
  MXylene = 'm-xylene',
  PXylene = 'p-xylene',
  Dipea = 'DIPEA',
  OneFiveDiazabicycloUndec7Ene = '1,5-diazabicyclo[5.4.0]undec-7-ene',
  Hexamethylphosphoramide = 'hexamethylphosphoramide',
  HexamethylphosphorousTriamide = 'hexamethylphosphorous triamide',
  HeavyWater = 'heavy water',
  Tris = 'TRIS',
  TrisHcl = 'TRIS HCl',
  SodiumChloride = 'Sodium-chloride',
  SodiumAcetate = 'Sodium-acetate',
  PotassiumChloride = 'Potassium-chloride',
  MonopotassiumPhosphate = 'Monopotassium phosphate',
  LithiumChloride = 'Lithium-chloride',
  GuanidineHcl = 'Guanidine HCl',
  DisodiumPhosphate = 'Disodium phosphate',
  DisodiumEdta = 'Disodium EDTA',
  AmmoniumSulfate = 'Ammonium-sulfate',
}
