function opts() {
    return [
        { name: 'showAtomIds',
        label: 'Show atom Ids',
        type: 'boolean',
        defaultValue: false,
        tab: 'debug' },
        { name: 'showBondIds',
        label: 'Show bonds Ids',
        type: 'boolean',
        defaultValue: false,
        tab: 'debug' },
        { name: 'showHalfBondIds',
        label: 'Show half bonds Ids',
        type: 'boolean',
        defaultValue: false,
        tab: 'debug' },
        { name: 'showLoopIds',
        label: 'Show loop Ids',
        type: 'boolean',
        defaultValue: false,
        tab: 'debug' },
        { name: 'showValenceWarnings',
        label: 'Show valence warnings',
        type: 'boolean',
        defaultValue: true,
        tab: 'render' },
        { name: 'atomColoring',
        label: 'Atom coloring',
        type: 'boolean',
        defaultValue: true,
        tab: 'render' },
        { name: 'hideChiralFlag',
        label: 'Do not show the Chiral flag',
        type: 'boolean',
        defaultValue: false,
        tab: 'render' },

		/* Atoms */
		{ name: 'carbonExplicitly',
		label: 'Display carbon explicitly',
		type: 'boolean',
		defaultValue: false,
		tab: 'atoms' },
		{ name: 'showCharge',
		label: 'Display charge',
		type: 'boolean',
		defaultValue: true,
		tab: 'atoms' },
		{ name: 'showValence',
		label: 'Display valence',
		type: 'boolean',
		defaultValue: true,
		tab: 'atoms' },
		{ name: 'showHydrogenLabels',
		label: 'Show hydrogen labels',
		type: 'string',
		defaultValue: 'on',
		values: ['off', 'Hetero', 'Terminal', 'Terminal and Hetero', 'on'],
		tab: 'atoms' },

		/* Bonds */
		{ name: 'aromaticCircle',
		label: 'Aromatic Bonds as circle',
		type: 'boolean',
		defaultValue: true,
		tab: 'bonds' },
		{ name: 'doubleBondWidth',
		label: 'Double bond width',
		type: 'field',
		defaultValue: 6,
		values: [0, 96],
		defaultMeasure: 'px',
		measures: ['cm', 'px', 'pt', 'inch'],
		tab: 'bonds' },
		{ name: 'bondThickness',
		label: 'Bond thickness',
		type: 'field',
		defaultValue: 2,
		values: [0, 96],
		defaultMeasure: 'px',
		measures: ['cm', 'px', 'pt', 'inch'],
		tab: 'bonds' },
		{ name: 'stereoBondWidth',
		label: 'Stereo (Wedge) bond width',
		type: 'field',
		defaultValue: 6,
		values: [0, 96],
		defaultMeasure: 'px',
		measures: ['cm', 'px', 'pt', 'inch'],
		tab: 'bonds' },

		{ name: 'font',
		label: 'Font',
		type: 'font',
		defaultValue: '30px Arial',
		tab: 'render' },
		{ name: 'fontsz',
		label: 'Font size',
		type: 'field',
		defaultValue: 13,
		values: [0, 96],
		defaultMeasure: 'px',
		measures: ['cm', 'px', 'pt', 'inch'],
		tab: 'render' },
		{ name: 'fontszsub',
		label: 'Sub font size',
		type: 'field',
		defaultValue: 13,
		values: [0, 96],
		defaultMeasure: 'px',
		measures: ['cm', 'px', 'pt', 'inch'],
		tab: 'render' },

		{ name: 'miewMode',
		label: 'Display mode',
		type: 'string',
		defaultValue: 'lines',
		values: ['lines', 'balls and sticks', 'licorice'],
		tab: 'miew' },
		{ name: 'miewTheme',
		label: 'Background color',
		type: 'string',
		defaultValue: 'light',
		values: ['light', 'dark'],
		tab: 'miew' },
		{ name: 'miewAtomLabel',
		label: 'Label coloring',
		type: 'string',
		defaultValue: 'bright',
		values: ['no', 'bright', 'inverse', 'black and white', 'black'],
		tab: 'miew' }
    ];
}

module.exports = opts;
