function opts() {
    return [
        { name: 'showAtomIds',
        label: 'Show atom Ids',
        type: 'boolean',
        defaultValue: false,
        tab: 'debug' },
        { name: 'showBondIds',
        label: 'Show bonds Ids',
        type: 'boolean',
        defaultValue: false,
        tab: 'debug' },
        { name: 'showHalfBondIds',
        label: 'Show half bonds Ids',
        type: 'boolean',
        defaultValue: false,
        tab: 'debug' },
        { name: 'showLoopIds',
        label: 'Show loop Ids',
        type: 'boolean',
        defaultValue: false,
        tab: 'debug' },
        { name: 'hideImplicitHydrogen',
        label: 'Hide implicit hydrogen',
        type: 'boolean',
        defaultValue: false,
        tab: 'render' },
        { name: 'hideTerminalLabels',
        label: 'Hide terminal labels',
        type: 'boolean',
        defaultValue: false,
        tab: 'render' },
        { name: 'showValenceWarnings',
        label: 'Show valence warnings',
        type: 'boolean',
        defaultValue: true,
        tab: 'render' },
        { name: 'atomColoring',
        label: 'Atom coloring',
        type: 'boolean',
        defaultValue: false,
        tab: 'render' },
        { name: 'hideChiralFlag',
        label: 'Do not show the Chiral flag',
        type: 'boolean',
        defaultValue: false,
        tab: 'render' }
    ];
}

module.exports = opts;
