function opts() {
    return [
        { name: 'showAtomIds',
        label: 'Show atom Ids',
        type: 'boolean',
        defaultValue: false,
        tab: 'debug' },
        { name: 'showBondIds',
        label: 'Show bonds Ids',
        type: 'boolean',
        defaultValue: false,
        tab: 'debug' },
        { name: 'showHalfBondIds',
        label: 'Show half bonds Ids',
        type: 'boolean',
        defaultValue: false,
        tab: 'debug' },
        { name: 'showLoopIds',
        label: 'Show loop Ids',
        type: 'boolean',
        defaultValue: false,
        tab: 'debug' },
        { name: 'showValenceWarnings',
        label: 'Show valence warnings',
        type: 'boolean',
        defaultValue: true,
        tab: 'render' },
        { name: 'atomColoring',
        label: 'Atom coloring',
        type: 'boolean',
        defaultValue: true,
        tab: 'render' },
        { name: 'hideChiralFlag',
        label: 'Do not show the Chiral flag',
        type: 'boolean',
        defaultValue: false,
        tab: 'render' },

		{ name: 'carbonExplicitly',
		label: 'Display carbon explicitly',
		type: 'boolean',
		defaultValue: false,
		tab: 'atoms' },
		{ name: 'hideTerminalLabels',
		label: 'Hide terminal carbon labels',
		type: 'boolean',
		defaultValue: false,
		tab: 'atoms' },
		{ name: 'showCharge',
		label: 'Display charge',
		type: 'boolean',
		defaultValue: true,
		tab: 'atoms' },
		{ name: 'showValence',
		label: 'Display valence',
		type: 'boolean',
		defaultValue: true,
		tab: 'atoms' },
		{ name: 'hydrogenLabels',
		label: 'Show hydrogen labels',
		type: 'number',
		defaultValue: 'on',
		values: ['off', 'Hetero', 'Terminal', 'Terminal and Hetero', 'on'],
		tab: 'atoms' },

		{ name: 'aromaticCircle',
		label: 'Aromatic Bonds as circle',
		type: 'boolean',
		defaultValue: true,
		tab: 'bonds' },

        { name: 'lineWidth',
        label: 'Letter-spacing',
        type: 'number',
        defaultValue: 2,
        values: [2, 6, 10],
        tab: 'render' },
		{ name: 'font',
		label: 'Font',
		type: 'string',
		defaultValue: '30px "Arial"',
		tab: 'render' },
		{ name: 'fontsz',
        label: 'Font size',
        type: 'number',
        defaultValue: 13,
        values: [10, 13, 20],
        tab: 'render' },
		{ name: 'fontszsub',
		label: 'Sub font size',
		type: 'number',
		defaultValue: 13,
		values: [10, 13, 20],
		tab: 'render' }
    ];
}

module.exports = opts;
