import { MonomerType } from '@utils/types';
import { createMonomerGroup } from './common';

export const Chem = createMonomerGroup(MonomerType.CHEM, {
  _4aPEGMal: {
    alias: '4aPEGMal',
    testId: '4aPEGMal___4-Arm PEG-Maleimide',
  },
  _4FB: { alias: '4FB', testId: '4FB___4-Formylbenzamide' },
  _5TAMRA: {
    alias: '5TAMRA',
    testId: '5TAMRA___5-Carboxytetramethylrhodamine',
  },
  A6OH: { alias: 'A6OH', testId: 'A6OH___6-amino-hexanol' },
  Az: { alias: 'Az', testId: 'Az___4-azidobutyric acid' },
  B7: { alias: 'B7', testId: 'B7___Biotin' },
  CHEM: {
    alias: 'CHEM',
    testId: 'CHEM___CHEM Test monomer',
  },
  SCY5: { alias: 'SCY5', testId: 'SCY5___Sulfo-Cyanine 5' },
  DOTA: { alias: 'DOTA', testId: 'DOTA___Tetraxetan' },
  EG: { alias: 'EG', testId: 'EG___Ethylene Glycol' },
  F1: { alias: 'F1', testId: '' },
  fisL: { alias: 'fisL', testId: 'flsL___Lactone fluorescein' },
  fisQ: { alias: 'fisQ', testId: 'flsQ___P-quinoid fluorescein' },
  iMe_dC2: { alias: 'iMe-dC2', testId: '' },
  hxy: { alias: 'hxy', testId: 'hxy___5-hexyn-1-ol' },
  Mal: { alias: 'Mal', testId: 'Mal___Maleimide' },
  MCC: {
    alias: 'MCC',
    testId: 'MCC___4-(N-maleimidomethyl)cyclohexane-1-carboxylate',
  },
  PEG_2: { alias: 'PEG-2', testId: 'PEG-2___Diethylene Glycol' },
  PEG_4: { alias: 'PEG-4', testId: 'PEG-4___Tetraethylene glycol' },
  PEG_6: { alias: 'PEG-6', testId: 'PEG-6___Hexaethylene glycol' },
  sDBL: { alias: 'sDBL', testId: 'sDBL___Symmetric Doubler' },
  SMCC: { alias: 'SMCC', testId: 'SMCC___SMCC' },
  SMPEG2: { alias: 'SMPEG2', testId: 'SMPEG2___SM(PEG)2' },
  SS3: { alias: 'SS3', testId: 'SS3___Dipropanol-disulfide' },
  Test_6_Ch: {
    alias: 'Test-6-Ch',
    testId: 'Test-6-Ch___Test-6-AP-Chem',
  },
  Sp18P: { alias: 'Sp18P', testId: 'Sp18P___Spacer 18' },
  SpC3: { alias: 'SpC3', testId: 'SpC3___C3 Spacer' },
  Dig: { alias: 'Dig', testId: 'Dig___Digoxigenin NHS ester' },
  JOE: {
    alias: 'JOE',
    testId: "JOE___6-carboxy-4',5'-dichloro-2',7'-dimethoxyfluorescein",
  },
  _5ROX: { alias: '5ROX', testId: '5ROX___5-carboxy-X-rhodamine' },
  TexRd: { alias: 'TexRd', testId: 'TexRd___Texas Red' },
  Cy3: { alias: 'Cy3', testId: 'Cy3___Cy3 dye' },
  Cy5: { alias: 'Cy5', testId: 'Cy5___Cy5 dye' },
  _56FAM: { alias: '56FAM', testId: "56FAM___Fluorescein (5' 6-FAM)" },
  HEX: { alias: 'HEX', testId: 'HEX___Hexachlorofluorescein' },
  TET: { alias: 'TET', testId: 'TET___Tetrachlorofluorescein' },
  Sp9: { alias: 'Sp9', testId: 'Sp9___Spacer 9' },
  Cy55: { alias: 'Cy55', testId: 'Cy55___Cy55 dye' },
  _2_Bio: { alias: '2-Bio', testId: '2-Bio___Dual Biotin' },
  UAmM: { alias: 'UAmM', testId: 'UAmM___Uni-Link Amino Modifier' },
  AF532: { alias: 'AF532', testId: 'AF532___Alexa Fluor 532 dye' },
  Acryd: { alias: 'Acryd', testId: 'Acryd___Acrydite' },
  AF546: { alias: 'AF546', testId: 'AF546___Alexa Fluor 546 dye' },
  AF647: { alias: 'AF647', testId: 'AF647___Alexa Fluor 647 dye' },
  ThiP: { alias: 'ThiP', testId: 'ThiP___Thiol Modifier C6 S-S' },
  AF488: { alias: 'AF488', testId: 'AF488___Alexa Fluor 488 dye' },
  AF594: { alias: 'AF594', testId: 'AF594___Alexa Fluor 594 dye' },
  IRD700: { alias: 'IRD700', testId: 'IRD700___IRDye 700' },
  IRD800: { alias: 'IRD800', testId: 'IRD800___IRDye 800' },
  RhoR: { alias: 'RhoR', testId: 'RhoR___Rhodamine Red' },
  RhoG: { alias: 'RhoG', testId: 'RhoG___Rhodamine Green' },
  YakYel: { alias: 'YakYel', testId: 'YakYel___Yakima Yellow' },
  dTp: { alias: 'dTp', testId: 'dTp___Dithiol modifier' },
  PCBio: { alias: 'PCBio', testId: 'PCBio___Photocleavable Biotin' },
  AF405: { alias: 'AF405', testId: 'AF405___Alexa Fluor 405 dye' },
  FAMN: { alias: 'FAMN', testId: 'FAMN___Fluorescein (FAMN)' },
  PCS: { alias: 'PCS', testId: 'PCS___PC Spacer' },
  dSBioT: { alias: 'dSBioT', testId: 'dSBioT___Desthiobiotin-TEG' },
  Dy750: { alias: 'Dy750', testId: 'Dy750___Dy 750' },
  BHQ_1: { alias: 'BHQ-1', testId: 'BHQ-1___Black Hole Quencher 1' },
  BHQ_2: { alias: 'BHQ-2', testId: 'BHQ-2___Black Hole Quencher 2' },
  BioP: { alias: 'BioP', testId: "BioP___5' Biotin" },
  _5hxy: { alias: '5hxy', testId: "5hxy___5' Hexynyl" },
  IRD800C: { alias: 'IRD800C', testId: 'IRD800C___IRDye 800CW' },
  Azd: { alias: 'Azd', testId: 'Azd___6-azidohexanoic acid' },
  BiAz: { alias: 'BiAz', testId: 'BiAz___Biotin Azide' },
  AzTAM: { alias: 'AzTAM', testId: 'AzTAM___5-TAMRA Azide' },
  FAMK: { alias: 'FAMK', testId: 'FAMK___6-FAM Azide' },
  A647: { alias: 'A647', testId: 'A647___ATTO 647N' },
  A532: { alias: 'A532', testId: 'A532___ATTO 532' },
  A590: { alias: 'A590', testId: 'A590___ATTO 590' },
  AR101: { alias: 'AR101', testId: 'AR101___ATTO Rho101' },
  _5BioT: { alias: '5BioT', testId: "5BioT___5' Biotin TEG" },
  A550: { alias: 'A550', testId: 'A550___ATTO 550' },
  A565: { alias: 'A565', testId: 'A565___ATTO 565' },
  A488: { alias: 'A488', testId: 'A488___ATTO 488' },
  A633: { alias: 'A633', testId: 'A633___ATTO 633' },
  DBCOT: { alias: 'DBCOT', testId: 'DBCOT___DBCO-TEG' },
  A700: { alias: 'A700', testId: 'A700___ATTO 700' },
  A425: { alias: 'A425', testId: 'A425___ATTO 425' },
  _5SUN: { alias: '5SUN', testId: "5SUN___5' SUN" },
  Bio: { alias: 'Bio', testId: "Bio___3' Biotin" },
  _3SpC3: { alias: '3SpC3', testId: "3SpC3___3' C3 Spacer" },
  _36FAM: { alias: '36FAM', testId: "36FAM___3' 6-FAM" },
  _3BioT: { alias: '3BioT', testId: "3BioT___3' Biotin TEG" },
  BHQ_3: { alias: 'BHQ-3', testId: 'BHQ-3___Black Hole Quencher 3' },
  C6: { alias: 'C6', testId: 'C6___1,6-Hexanediol' },
  ChTEG: { alias: 'ChTEG', testId: 'ChTEG___Cholesterol-TEG' },
  AmMO: { alias: 'AmMO', testId: 'AmMO___3-(3-aminopropoxy)propane-1,2-diol' },
  MGBEc: { alias: 'MGBEc', testId: 'MGBEc___MGBEc' },
  // for library update test, doesn't exist initially
  _CHEM1: { alias: '_CHEM1', testId: '_CHEM1____CHEM1' },
});

export type ChemType = typeof Chem;
