import i18n from 'i18next';
import ICU from 'i18next-icu';
import { initReactI18next } from 'react-i18next';

// Generated by scripts/generate-locale-resources.mjs from whatever locale
// directories exist under src/locales/ — see that file for why imports stay
// static (Rollup tree-shaking in the English-only default build) despite
// the locale list itself being discovered, not hand-maintained. Adding or
// removing a language is a src/locales/<code>/ directory change plus
// `npm run i18n:generate`, not an edit to this file.
import {
  BASE_RESOURCES,
  EXTRA_LOCALE_RESOURCES,
} from './localeResources.generated';

export const defaultNS = 'common';

// English-only is the default build. Opting into every other locale is a
// build-time flag rather than the default, so the common case ships the
// smallest bundle. Read once as a plain boolean so every branch below folds
// to a literal after @rollup/plugin-replace substitutes the env var at
// build time.
const MULTI_LANGUAGE_BUILD =
  process.env.KETCHER_MULTI_LANGUAGE_BUILD === 'true';

type LocaleResources = typeof BASE_RESOURCES;

// Typed as if every generated locale is always present, even though only
// 'en' is genuinely available at runtime in the default single-language
// build — the type only needs to describe the full (non-flagged) shape so
// SupportedLanguage/isSupportedLanguage keep working unchanged across both
// build variants.
export const resources: {
  en: LocaleResources;
} & typeof EXTRA_LOCALE_RESOURCES = MULTI_LANGUAGE_BUILD
  ? { en: BASE_RESOURCES, ...EXTRA_LOCALE_RESOURCES }
  : ({ en: BASE_RESOURCES } as {
      en: LocaleResources;
    } & typeof EXTRA_LOCALE_RESOURCES);

export interface SupportedLanguage {
  code: keyof typeof resources;
  label: string;
}

// A language's dropdown label is its own endonym (Intl.DisplayNames asked,
// in that same locale, "what do you call yourself") so a newly generated
// locale gets a sensible label with zero manual code changes. `overrides`
// exists only where that computed default would change an already-shipped
// label — e.g. Intl.DisplayNames renders 'zh-CN' as "中文（中国）", not the
// "简体中文" this UI has always shown — never add a new language here just
// to give it a label; let the computed default handle it. It's passed in
// rather than module-scope so the override string itself stays confined to
// the MULTI_LANGUAGE_BUILD branch below (module-scope would make it a live
// reference Rollup can't tree-shake out of the English-only default build,
// even though the override is only ever read for a non-English code).
function languageLabel(
  code: string,
  overrides: Partial<Record<string, string>> = {},
): string {
  if (overrides[code]) {
    return overrides[code] as string;
  }
  try {
    return new Intl.DisplayNames([code], { type: 'language' }).of(code) ?? code;
  } catch {
    return code;
  }
}

// EXTRA_LOCALE_RESOURCES must only be referenced inside a MULTI_LANGUAGE_BUILD
// branch (never unconditionally at module scope) — once @rollup/plugin-replace
// substitutes the flag with a literal, Rollup's tree-shaking needs every
// reference to the non-English JSON modules (and non-English label text) to
// be confined to the now-unreachable branch to drop them from the
// English-only default build.
export const SUPPORTED_LANGUAGES: SupportedLanguage[] = MULTI_LANGUAGE_BUILD
  ? [
      { code: 'en', label: languageLabel('en') },
      ...(
        Object.keys(EXTRA_LOCALE_RESOURCES) as Array<
          keyof typeof EXTRA_LOCALE_RESOURCES
        >
      ).map((code) => ({
        code,
        label: languageLabel(code, { 'zh-CN': '简体中文' }),
      })),
    ]
  : [{ code: 'en', label: languageLabel('en') }];

const DEFAULT_LANGUAGE = 'en';
const LANGUAGE_STORAGE_KEY = 'ketcher-language';

function isSupportedLanguage(value: unknown): value is keyof typeof resources {
  return SUPPORTED_LANGUAGES.some((language) => language.code === value);
}

function getStoredLanguage(): keyof typeof resources {
  if (typeof window === 'undefined') {
    return DEFAULT_LANGUAGE;
  }
  const stored = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
  return isSupportedLanguage(stored) ? stored : DEFAULT_LANGUAGE;
}

if (!i18n.isInitialized) {
  i18n
    .use(ICU)
    .use(initReactI18next)
    .init({
      resources,
      lng: getStoredLanguage(),
      fallbackLng: DEFAULT_LANGUAGE,
      defaultNS,
      ns: Object.keys(resources.en),
      interpolation: {
        escapeValue: false,
      },
      returnEmptyString: false,
      saveMissing: process.env.NODE_ENV === 'development',
      missingKeyHandler:
        process.env.NODE_ENV === 'development'
          ? (_lngs, ns, key) => {
              console.warn(`[i18n] Missing key "${key}" in namespace "${ns}"`);
            }
          : undefined,
    });

  if (typeof window !== 'undefined') {
    i18n.on('languageChanged', (lng) => {
      window.localStorage.setItem(LANGUAGE_STORAGE_KEY, lng);
    });
  }
}

export default i18n;
