name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 18.14.0
        uses: actions/setup-node@v2
        with:
          node-version: 18.14.0

      - name: Get npm cache directory path
        id: npm-cache-dir-path
        run: echo "::set-output name=dir::$(npm config get cache)"

      - uses: actions/cache@v4
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install Dependencies
        run: npm ci

      - name: Run build
        env:
          NODE_ENV: production
          CI: "false"
        run: npm run build

      - name: Create ketcher-core tarball
        run: >
          tar -C packages/ketcher-core
          -czf ketcher-core.tar.gz
          dist README.md package.json

      - name: Create ketcher-react tarball
        run: >
          tar -C packages/ketcher-react
          -czf ketcher-react.tar.gz
          dist README.md package.json

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ketcher-core.tar.gz
            ketcher-react.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
